spring:
  application:
    name: rag-service

  datasource:
    url: jdbc:postgresql://localhost:5433/ragdb
    username: raguser
    password: ragpass

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  ai:
    ollama:
      base-url: http://localhost:11434

      chat:
        model: llama3

      embedding:
        model: nomic-embed-text

    vectorstore:
        pgvector:
          initialize-schema: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
